# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
   config.vm.box = "ubuntu/focal64"
   config.vm.synced_folder "../secrets/", "/secrets"
   config.vm.provision :shell, path: "bootstrap.sh"
   config.vm.provision "shell", inline: "sudo apt install swapspace -y"
   config.vm.provision "shell", run: "always", path: "reboot-provision.sh"
   config.vm.network "private_network", ip: "10.50.0.2"
   config.vm.network "forwarded_port", guest: 8100, host: 8100, host_ip: "0.0.0.0"
   config.vm.provider "virtualbox" do |vb|
     vb.name = "coffeeshop"
     vb.memory = "2048"
    vb.customize ["modifyvm", :id, "--memory", "2048"]
   end end
