# Generated by Django 2.1.4 on 2020-12-22 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coffeeshop', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='unit_price',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
    ]
