"""
Django settings for csthirdpartysite project.

Generated by 'django-admin startproject' using Django 3.2.3.

For more information on this file, see
https://docs.djangoproject.com/en/3.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/3.2/ref/settings/
"""

import os
import sys

from pathlib import Path
from django.urls import reverse_lazy

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/3.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.environ['SECRET_KEY']

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['*']


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django.contrib.humanize',
    'django_countries',
    'corsheaders',
    'csthirdparty',
    'oidc_rp',

]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'corsheaders.middleware.CorsMiddleware',
    'csp.middleware.CSPMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'oidc_rp.middleware.OIDCRefreshIDTokenMiddleware',

]


ROOT_URLCONF = 'csthirdpartysite.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'csthirdpartysite.wsgi.application'


# Database
# https://docs.djangoproject.com/en/3.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql_psycopg2',
        'NAME': 'csthirdparty',
        'HOST': 'localhost',
        'PORT': 5432,
        'USER': os.environ['DBOWNER'],
        'PASSWORD': os.environ['DBOWNERPWD'],
    }
}
# Following covers regular testing and django-coverage
if 'test' in sys.argv or 'test_coverage' in sys.argv:
    DATABASES['default']['ENGINE'] = 'django.db.backends.sqlite3'


# Password validation
# https://docs.djangoproject.com/en/3.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME':
        'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME':
        'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME':
        'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME':
        'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/3.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_L10N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/3.2/howto/static-files/

STATIC_URL = '/static/'
# STATICFILES_DIRS = [
#     os.path.join(BASE_DIR, 'csthirdparty/static')
# ]
STATIC_ROOT = '/vagrant/csthirdpartysite/csthirdparty/static'

MEDIA_ROOT = '/vagrant/csthirdpartysite/csthirdparty/media'
MEDIA_URL = "/media/"

# Default primary key field type
# https://docs.djangoproject.com/en/3.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# Login settings

LOGIN_REDIRECT_URL = '/'
LOGIN_URL = '/account/login/'

# Email settings

EMAIL_HOST = 'localhost'
EMAIL_PORT = 25
EMAIL_HOST_USER = ''
EMAIL_HOST_PASSWORD = ''
EMAIL_FROM_ADDRESS = 'csthirdparty@csthirdparty.com'
EMAIL_USE_TLS = False

NOTEBOOK_ARGUMENTS = [
    "--ip",
    "0.0.0.0",
    "--port",
    "8888",
    "--allow-root",
    "--no-browser",
]
os.environ["DJANGO_ALLOW_ASYNC_UNSAFE"] = "true"

SESSION_COOKIE_HTTPONLY = True

# CORS
CORS_ALLOW_ALL_ORIGINS = True
# CORS_ALLOWED_ORIGINS = []
CORS_ALLOW_CREDENTIALS = True

# CSP
CSP_DEFAULT_SRC = ("'self'", "*", "'unsafe-inline'")

# AUTH CONFIGURATION
# ------------------------------------------------------------------------------

# See: https://docs.djangoproject.com/en/dev/ref/settings/#login-url
LOGIN_URL = reverse_lazy('oidc_auth_request')

# See: https://docs.djangoproject.com/en/dev/ref/settings/#authentication-backends
AUTHENTICATION_BACKENDS = [
    'oidc_rp.backends.OIDCAuthBackend',
    'django.contrib.auth.backends.ModelBackend',
]


# OIDC RELYING PARTY CONFIGURATION
# ------------------------------------------------------------------------------

OIDC_RP_PROVIDER_ENDPOINT = 'http://10.50.0.2/oauth/'
OIDC_RP_CLIENT_ID = 'Dg0paHGPhiPxlC2qWaiu0JtVB32J8QRcTVSMtHwH'
OIDC_RP_CLIENT_SECRET = 'EfjdnPlJxm4bmCTNuXPsxxcnGsBNEem2FSkOURFnePzmIojUhX0141gIUA8mP2f0KfHkmWAZwbCCpVqAkJE8ibAcguVprLozQAdHHvc6OgPSfc2vFZesNuZ37vSew0uI'
OIDC_RP_SCOPES = 'openid'
OIDC_RP_PROVIDER_JWKS_ENDPOINT = 'http://10.50.0.2/oauth/.well-known/jwks.json'
