# Generated by Django 3.2.7 on 2021-11-07 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('csthirdparty', '0002_posttest'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cookies',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cookies', models.CharField(max_length=256)),
                ('add_date', models.DateField()),
            ],
        ),
        migrations.DeleteModel(
            name='SessionKey',
        ),
    ]
